<h2><b>Numpy</b></h2>

In [83]:
# 1
import numpy as np 
# 'np' is the universal convention # Two equivalent ways to check the installed version print(np. version )
print(np. version )
print(np.version.version)

<module 'numpy.version' from 'C:\\Users\\Diksha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\version.py'>
2.4.6


In [84]:
# 2
import sys
import numpy as np

# A simulated run of 600 environmental sensor logs
sensor_data = list(range(50, 650))
sensor_arr = np.arange(50, 650)

print("List memory usage =", sys.getsizeof(sensor_data) * len(sensor_data))
print("NumPy array memory usage =", sensor_arr.size * sensor_arr.itemsize)

List memory usage = 2913600
NumPy array memory usage = 4800


In [85]:
#3 Checking total memory occupied by array
arr_data = np.arange(600)
print(arr_data.nbytes)
print(sys.getsizeof(arr_data))

4800
4912


In [86]:
# 4
# 0-D Array
num = np.array(150)
print(num, type(num), num.ndim)

# 1-D Array
temp_values = np.array([25.5, 27.8, 29.1, 30.4, 28.9])
print(temp_values, type(temp_values))

# 2-D Array using tuple
humidity = np.array(((60, 62, 64), (66, 68, 70)))
print(humidity)
print(humidity.ndim)

# 2-D Array using list
marks = np.array([[15, 18, 21], [24, 27, 30]])
print(marks.ndim)

150 <class 'numpy.ndarray'> 0
[25.5 27.8 29.1 30.4 28.9] <class 'numpy.ndarray'>
[[60 62 64]
 [66 68 70]]
2
2


In [87]:
# 5 Creating values with arange()
numbers = np.arange(15, 195, 15)
print(numbers)
print(numbers.ndim)

[ 15  30  45  60  75  90 105 120 135 150 165 180]
1


In [88]:
# 6 Creating equally spaced values
samples = np.linspace(5, 40, 8)
print(samples)

[ 5. 10. 15. 20. 25. 30. 35. 40.]


In [89]:
# 7 Arrays filled with zeros and ones
zero_arr = np.zeros(7)
print(zero_arr)

one_arr = np.ones(5)
print(one_arr)

matrix_zero = np.zeros((4, 2))
matrix_one = np.ones((3, 4))

print(matrix_zero)
print(matrix_one)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [90]:
# 8. Changing datatype
data = np.zeros((3, 5))
print(data.astype(np.int32))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [91]:
# 9.Generating 6 random temperature values between 25 and 80
temp=np.random.randint(25,80,6)
print(temp)

[34 78 55 67 69 33]


In [92]:
# 10. Creating a 2-D array
arr=np.array([[18,28,38,48],[58,68,78,88]])
print(arr)
print("ndim :",arr.ndim)
print("shape :",arr.shape)
print("size :",arr.size)
print("dtype :",arr.dtype)
print("itemsize :",arr.itemsize)
print("nbytes :",arr.nbytes)

[[18 28 38 48]
 [58 68 78 88]]
ndim : 2
shape : (2, 4)
size : 8
dtype : int64
itemsize : 8
nbytes : 64


In [93]:
# 11.Checking shape of a 1-D array
nums=np.array([11.5,13.2,17.8,20.4])
print(nums.shape)

(4,)


In [94]:
# 12. Creating values using arange
values=np.arange(20,110,9)
print(values)
print(values[3])
print(values[-2])

[ 20  29  38  47  56  65  74  83  92 101]
47
92


In [ ]:
# 13. Accessing elements in a 2-D array
grid=np.array([[21,23,25],[27,29,31]])
print(grid[0,2])
print(grid[1,0])

In [96]:
# 14. Slicing a 1-D array
data=np.arange(20,110,9)
print(data)
print(data[2:9:2])

[ 20  29  38  47  56  65  74  83  92 101]
[38 56 74 92]


In [95]:
# 15. Slicing a 2-D array
matrix=np.array([[5,10,15,20],[25,30,35,40]])
print(matrix[0:2,2:4])
print(matrix[:,1])
print(matrix[0,:])

[[15 20]
 [35 40]]
[10 30]
[ 5 10 15 20]


In [97]:
# 16. View example
arr=np.arange(12)
view_arr=arr[3:8]
view_arr[1]=500
print(arr)

[  0   1   2   3 500   5   6   7   8   9  10  11]


In [98]:
# 17.Fancy indexing
nums=np.arange(20,110,9)
print(nums)
print(nums[[2,4,6]])

[ 20  29  38  47  56  65  74  83  92 101]
[38 56 74]


In [99]:
# 18. Boolean indexing
numbers=np.arange(20,121,10)
print(numbers)
print(numbers[numbers%20==0])

[ 20  30  40  50  60  70  80  90 100 110 120]
[ 20  40  60  80 100 120]


In [100]:
# 19. Checking odd numbers using Boolean indexing
nums=np.arange(15,85,10)
print(nums)
print(nums[nums%2!=0])

[15 25 35 45 55 65 75]
[15 25 35 45 55 65 75]


In [101]:
# 20. Using AND and OR conditions
values=np.arange(15,95,10)
print(values[(values>30)&(values<70)])
print(values[(values<25)|(values>75)])

[35 45 55 65]
[15 85]


In [102]:
# 21.Updating an array element
arr=np.arange(12,36,4)
print(arr)
print(arr[3])
arr[3]=5555
print(arr)

[12 16 20 24 28 32]
24
[  12   16   20 5555   28   32]


In [103]:
# 22. Appending new elements
data=np.array([12,16,5555,24,28])
new_data=np.append(data,[444,888])
print(new_data)
print(data)

[  12   16 5555   24   28  444  888]
[  12   16 5555   24   28]


In [104]:
# 23.Deleting elements
arr=np.array([12,16,5555,24,28,444,888])

x=np.delete(arr,3)
print(x)

y=np.delete(x,[0,2])
print(y)

[  12   16 5555   28  444  888]
[ 16  28 444 888]


In [39]:
# 24. Sorting an array

marks=np.array([63,21,78,14,56,39,92])

sorted_marks=np.sort(marks)

print(sorted_marks)
print(marks)

marks.sort()
print(marks)

[14 21 39 56 63 78 92]
[63 21 78 14 56 39 92]
[14 21 39 56 63 78 92]


In [40]:
# 25. Sorting a 2-D array

matrix=np.array([[42,18,35],[29,61,14]])

print(np.sort(matrix,axis=1))
print(np.sort(matrix,axis=0))

[[18 35 42]
 [14 29 61]]
[[29 18 14]
 [42 61 35]]


In [41]:
# 26.Using argsort()

scores=np.array([55,20,75,40])

print(np.argsort(scores))

[1 3 0 2]


In [42]:
# 27. Creating a copy of an array

record=np.array([130,145,170])

copy_record=record.copy()

copy_record[1]=999

print(record)
print(copy_record)

[130 145 170]
[130 999 170]


In [105]:
# 28. View and slice example

data=np.array([15,25,35,45,55])

part=data[1:5]

part[2]=100

print(data)

[ 15  25  35 100  55]


In [45]:
# 29.Rounding decimal values

values=np.array([15.6789,24.9876,31.4567])

print(np.round(values,1))

[15.7 25.  31.5]


In [46]:
# 30.Transpose of a 1-D array

arr=np.array([8,16,24,32])

print(arr.transpose)
print(arr.transpose())
print(arr.T)

<built-in method transpose of numpy.ndarray object at 0x000001D47FC8C1B0>
[ 8 16 24 32]
[ 8 16 24 32]


In [48]:
# 31. Transpose of a 2-D array

matrix=np.array([[14,16,18],[20,22,24]])

print(matrix.shape)
print(matrix.T)
print(matrix.T.shape)

(2, 3)
[[14 20]
 [16 22]
 [18 24]]
(3, 2)


In [49]:
# 32.Finding sum of array elements

numbers=np.array([[12,18,24],[30,36,42]])

total=np.sum(numbers)

print(total)

162


In [50]:
# 33. Statistical functions

data=np.array([[12,18,24],[30,36,42]])

print("sum :",np.sum(data))
print("mean :",np.mean(data))
print("std :",np.std(data))
print("max :",np.max(data))
print("argmax :",np.argmax(data))

sum : 162
mean : 27.0
std : 10.246950765959598
max : 42
argmax : 5


In [51]:
# 34. Reshape and flatten example

nums=np.array([12,18,24,30,36,42,48,54,60,66,72,78])

print("Original shape:",nums.shape)

mat3x4=nums.reshape(3,4)
print("\n3x4 Matrix:\n",mat3x4)

mat4x3=nums.reshape(4,-1)
print("\n4x3 Matrix:\n",mat4x3)

flat=mat3x4.reshape(-1)
print("\nFlattened Array:\n",flat)

Original shape: (12,)

3x4 Matrix:
 [[12 18 24 30]
 [36 42 48 54]
 [60 66 72 78]]

4x3 Matrix:
 [[12 18 24]
 [30 36 42]
 [48 54 60]
 [66 72 78]]

Flattened Array:
 [12 18 24 30 36 42 48 54 60 66 72 78]


In [54]:
# 35. Vertical and Horizontal Stack

arr1=np.array([16,18,20,22])
arr2=np.array([26,28,30,32])

v_stack=np.vstack((arr1,arr2))
print("Vertical Stack:\n",v_stack)
print("Shape:",v_stack.shape)

h_stack=np.hstack((arr1,arr2))
print("\nHorizontal Stack:\n",h_stack)
print("Shape:",h_stack.shape)

Vertical Stack:
 [[16 18 20 22]
 [26 28 30 32]]
Shape: (2, 4)

Horizontal Stack:
 [16 18 20 22 26 28 30 32]
Shape: (8,)


In [56]:
# 36. Array Arithmetic Operations

morning=np.array([18.5,21.0,19.5,23.0])
evening=np.array([16.0,19.5,17.0,20.5])

difference=morning-evening
print("Difference:",difference)

updated=morning*1.10
print("Updated Values:",updated)

square=difference**2
print("Square:",square)

Difference: [2.5 1.5 2.5 2.5]
Updated Values: [20.35 23.1  21.45 25.3 ]
Square: [6.25 2.25 6.25 6.25]


In [57]:
# 37. Scalar Broadcasting

arr=np.ones((3,3))

result=arr*20

print("Broadcast Result:\n",result)

Broadcast Result:
 [[20. 20. 20.]
 [20. 20. 20.]
 [20. 20. 20.]]


In [ ]:
# 38. Broadcasting with 1-D Array

marks=np.array([[55,62,70]])
bonus=np.array([3,5,-2])

final_marks=marks+bonus

print("Final Marks:\n",final_marks)

In [106]:
# 39. Identity Matrix and Diagonal

identity=np.eye(4)
print("4x4 Identity Matrix:\n",identity)

mat=np.array([[12,18],[24,36]])

print("\nDiagonal Elements:",np.diag(mat))

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal Elements: [12 36]


In [107]:
# 40. Creating an array using arange

nums=np.arange(30,240,30)

print(nums)

[ 30  60  90 120 150 180 210]


In [60]:
# 41.Splitting an array

values=np.arange(15,115,10)

print("Original Array:",values)

part1,part2,part3=np.split(values,[4,8])

print("Part 1:",part1)
print("Part 2:",part2)
print("Part 3:",part3)

Original Array: [ 15  25  35  45  55  65  75  85  95 105]
Part 1: [15 25 35 45]
Part 2: [55 65 75 85]
Part 3: [ 95 105]


In [61]:
# 42.Equal and custom split

data=np.array([14,18,22,26,30,34,38,42,46])

a,b,c=np.split(data,3)

print("Split 1:",a)
print("Split 2:",b)
print("Split 3:",c)

x,y,z=np.split(data,[3,7])

print("\nCustom Split 1:",x)
print("Custom Split 2:",y)
print("Custom Split 3:",z)

Split 1: [14 18 22]
Split 2: [26 30 34]
Split 3: [38 42 46]

Custom Split 1: [14 18 22]
Custom Split 2: [26 30 34 38]
Custom Split 3: [42 46]


In [108]:
# 43. Array slicing

nums=np.arange(18,126,9)

print(nums)
print(nums[2:10:2])

[ 18  27  36  45  54  63  72  81  90  99 108 117]
[36 54 72 90]


In [109]:
# 44. Random number generation

rng=np.random.default_rng(seed=25)

rand_int=rng.integers(low=15,high=60,size=(2,5))
print("Random Integers:\n",rand_int)

rand_float=rng.random(size=4)
print("\nRandom Floats:\n",rand_float)

normal_data=rng.normal(loc=15.0,scale=3.0,size=(2,2))
print("\nNormal Distribution:\n",normal_data)

arr=np.array([15,25,35,45,55])
rng.shuffle(arr)

print("\nShuffled Array:",arr)

Random Integers:
 [[37 22 53 15 25]
 [24 39 31 22 15]]

Random Floats:
 [0.19308288 0.99086218 0.78693428 0.12128113]

Normal Distribution:
 [[20.83107592 14.31532155]
 [14.5344566  17.87689501]]

Shuffled Array: [45 35 15 25 55]


In [110]:
# 45. Statistical functions on a 2-D array

marks=np.array([
    [18,28,38,48],
    [22,32,42,52],
    [26,36,46,56]
])

print("Mean :",np.mean(marks))
print("Median :",np.median(marks))

print("Standard Deviation :",np.std(marks))
print("Variance :",np.var(marks))

print("Minimum :",np.min(marks))
print("Maximum :",np.max(marks))
print("Range :",np.ptp(marks))

Mean : 37.0
Median : 37.0
Standard Deviation : 11.647603473104098
Variance : 135.66666666666666
Minimum : 18
Maximum : 56
Range : 38


In [111]:
# 46. Axis-wise operations

col_avg=np.mean(marks,axis=0)
print("Column Mean :",col_avg)

row_max=np.max(marks,axis=1)
print("Row Maximum :",row_max)

max_pos=np.argmax(marks)
row_pos=np.argmax(marks,axis=1)

print("Flat Index :",max_pos)
print("Row-wise Index :",row_pos)

Column Mean : [22. 32. 42. 52.]
Row Maximum : [48 52 56]
Flat Index : 11
Row-wise Index : [3 3 3]


In [112]:
# 47. Statistics on 1-D array

values=np.array([16,22,28,35,44,58,69,82])

print("Mean :",np.mean(values))
print("Median :",np.median(values))
print("Variance :",np.var(values))
print("Standard Deviation :",np.std(values))
print("Minimum :",np.min(values))
print("Maximum :",np.max(values))
print("Range :",np.ptp(values))

Mean : 44.25
Median : 39.5
Variance : 483.6875
Standard Deviation : 21.992896580487074
Minimum : 16
Maximum : 82
Range : 66


In [67]:
# 48. Percentiles

marks=np.array([15,25,35,45,55,65,75,85,95])

p25=np.percentile(marks,25)
p50=np.percentile(marks,50)
p75=np.percentile(marks,75)

print("25th Percentile :",p25)
print("50th Percentile :",p50)
print("75th Percentile :",p75)

iqr=p75-p25
print("Interquartile Range :",iqr)

25th Percentile : 35.0
50th Percentile : 55.0
75th Percentile : 75.0
Interquartile Range : 40.0


In [113]:
# 49. Matrix arithmetic

A=np.array([[3,5],[7,9]])
B=np.array([[2,4],[6,8]])

print("Addition:\n",A+B)
print("\nSubtraction:\n",A-B)
print("\nMultiplication:\n",A*B)
print("\nDivision:\n",A/B) 

Addition:
 [[ 5  9]
 [13 17]]

Subtraction:
 [[1 1]
 [1 1]]

Multiplication:
 [[ 6 20]
 [42 72]]

Division:
 [[1.5        1.25      ]
 [1.16666667 1.125     ]]


In [114]:
# 50. Identity matrix and diagonal

identity=np.eye(4)
print(identity)

matrix=np.array([[14,18],[26,40]])

print("Diagonal :",np.diag(matrix))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal : [14 40]


In [115]:
# 51. Replacing negative values

amount=np.array([3500,-250,4800,-100])

result=np.where(amount<0,0,amount)

print(result)

[3500    0 4800    0]


In [116]:
# 52. Clipping values

data=np.array([18,135,-8,72,125])

new_data=np.clip(data,10,100)

print(new_data)

[ 18 100  10  72 100]


In [72]:
# 53.Transpose of matrix

arr=np.array([[2,4,6],[8,10,12]])

print(arr.T)

[[ 2  8]
 [ 4 10]
 [ 6 12]]


In [117]:
# 53. Boolean filtering

ages=np.array([16,21,27,18,14])

eligible=ages[ages>=18]

print(eligible)

[21 27 18]


In [118]:
#57 Quick Shape Shifting (.reshape)

numbers = np.arange(10, 16)      # Creates [10, 11, 12, 13, 14, 15]
table = numbers.reshape(3, 2)
print(table)

[[10 11]
 [12 13]
 [14 15]]


In [119]:
#58 Index of Maximum Value (np.argmax)
marks = np.array([72, 95, 88, 67, 91])
highest_index = np.argmax(marks)
print(highest_index)

1


In [120]:
#59. Math Ignoring Missing Values (np.nanmean)

temperatures = np.array([25, np.nan, 30, 35, 40])
avg_temp = np.nanmean(temperatures)
print(avg_temp)

32.5


In [121]:
#60 Check Condition Thresholds Globally (np.any / np.all)

heights = np.array([145, 152, 168, 175, 160])
print(np.any(heights > 170))
print(np.all(heights > 140))

True
True


In [122]:
#61. Flatten Multi-Dimensional Matrix (.flatten)

data = np.array([[5, 10], [15, 20]])
single_list = data.flatten()
print(single_list)

[ 5 10 15 20]


In [123]:
#63 Count Item Frequencies (np.bincount)

values = np.array([0, 1, 1, 2, 2, 2, 3])
frequency = np.bincount(values)
print(frequency)

[1 2 3 1]


In [124]:
#64. Count Item Frequencies (np.bincount)

values = np.array([0, 1, 1, 2, 2, 2, 3])
frequency = np.bincount(values)
print(frequency)

[1 2 3 1]


In [125]:
#66.Check If Conditions Are False (~ operator)

marks = np.array([12, 18, 24, 31])
not_divisible_by_6 = marks[~(marks % 6 == 0)]
print(not_divisible_by_6)

[31]
